---
language: csharp

mono:
  - 4.6.1
  - 4.8.0
  - weekly # => "stable release"
  - latest # => "latest commits"

os:
  - osx
  - linux

dist: trusty
sudo: required

dotnet: 1.0.1

install:
  # See details at https://github.com/NuGet/Home/issues/2163
  # this may be required because of an underlying bug in mono. It may
  # also be induced by us because we have an extra nuget.config source.
  - ulimit -n 2048

  - rvm install 2.2.3
  - gem install bundler

script:
 - bundle && bundle exec rake

matrix:
  fast_finish: true # just fail immediately if at least one job fails
  allow_failures:
    - mono: latest
    - mono: weekly
