language: csharp
dist: trusty
sudo: false
dotnet: 2.0.3

matrix:
  fast_finish: true
  
  include:
    - os: linux
      mono: 5.4.1
    - os: linux
      mono: weekly
    - os: linux
      mono: latest
    - os: osx
      osx_image: xcode9.1
      mono: 5.4.1
      env: MONO_BASE_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/
    - os: osx
      osx_image: xcode9.1
      mono: latest
      env: MONO_BASE_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/

  allow_failures:
    - os: osx
    - mono: weekly
    - mono: latest

addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

script:
  - ./build.sh