language: csharp
dist: trusty

sudo: false

os:
 - osx
 - linux

script: 
  - ./build.sh

matrix:
  include:
    - mono: 4.8.1
      dotnet: 1.0.4
    - mono: weekly
      dotnet: 1.0.4
    - mono: latest
      dotnet: 1.0.4
    - mono: weekly
      dotnet: 2.0.0

  allow_failures:
    - mono: latest
    - mono: weekly
    - os: osx