---
language: csharp

os:
  - osx
  - linux

dist: trusty
sudo: required

dotnet: 1.0.0-preview2-003121

mono:
  - 4.6.1
  - 4.8.0
  - weekly
  - latest

env:
  - CLI_VERSION=1.0.0-rc4-004771

matrix:
  fast_finish: true # just fail immediately if at least one job fails
  allow_failures:
    - mono: weekly
    - mono: latest
    
install:
  - rvm install 2.2.3
  - gem install bundler
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  

script:
 - bundle && bundle exec rake
