language: csharp
dist: trusty
sudo: false

script: 
  - ./build.sh

matrix:
  include:
    - os: linux
      mono: 4.8.1
      dotnet: 1.0.4
    - os: osx
      mono: 4.8.1
      dotnet: 1.0.4
    - os: linux
      mono: weekly
      dotnet: 1.0.4
    - os: linux
      mono: latest
      dotnet: 1.0.4
    - os: linux
      mono: 4.8.1
      dotnet: 2.0.0

  allow_failures:
    - os: osx
    - mono: weekly
    - mono: latest
    - dotnet: 2.0.0