---
language: csharp

matrix:
  include:      
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      env:
        - CLI_VERSION=1.0.0-rc4-004771
    - os: osx # OSX 10.11
      osx_image: xcode7.3
      dotnet: 1.0.0-preview2-003121
      env:
        - CLI_VERSION=1.0.0-rc4-004771

install:
  - rvm install 2.2.3
  - gem install bundler
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  

script:
 - bundle && bundle exec rake
 - ./build.sh
