language: csharp
dist: trusty
sudo: false
dotnet: 2.0.3

matrix:
  fast_finish: true
  
  include:
    - os: linux
      mono: 5.4.1
    - os: linux
      mono: weekly
    - os: linux
      mono: latest
    - os: osx
      osx_image: xcode9.1
      mono: 5.4.1
    - os: osx
      osx_image: xcode9.1
      mono: latest

  allow_failures:
    - os: osx
    - mono: weekly
    - mono: latest

addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 1.1.2 --install-dir .dotnet --no-path  --shared-runtime; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then export PATH="$PWD/.dotnet":$PATH; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then export DOTNET_CLI_TELEMETRY_OPTOUT=1; fi

script:
  - ./build.sh