language: csharp
dist: trusty
sudo: false

os:
 - linux
 - osx

mono:
  - 4.8.1
  - weekly
  - latest

dotnet: 1.0.4

matrix:
  allow_failures:
    - os: osx
    - mono: weekly
    - mono: latest

script: 
  - ./build.sh